### ISSUE TITLE
debian 11 compilation error

### ISSUE THREAD

**Issue by baton411** [1265578519/OpenTracker#5]
When compiling on debian 11 it gives an error:

root@srv00:/home/OpenTracker-master/opentracker# make
Makefile:100: warning: ignoring prerequisites on suffix rule definition
Makefile:97: warning: ignoring prerequisites on suffix rule definition
Makefile:100: warning: ignoring prerequisites on suffix rule definition
Makefile:100: warning: ignoring prerequisites on suffix rule definition
Makefile:97: warning: ignoring prerequisites on suffix rule definition
Makefile:100: warning: ignoring prerequisites on suffix rule definition
cc -c -o opentracker.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE opentracker.c
cc -c -o trackerlogic.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE trackerlogic.c
cc -c -o scan_urlencoded_query.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE scan_urlencoded_query.c
cc -c -o ot_mutex.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_mutex.c
cc -c -o ot_stats.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_stats.c
cc -c -o ot_vector.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_vector.c
cc -c -o ot_clean.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_clean.c
cc -c -o ot_udp.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_udp.c
cc -c -o ot_iovec.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_iovec.c
cc -c -o ot_fullscrape.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_fullscrape.c
cc -c -o ot_accesslist.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_accesslist.c
cc -c -o ot_http.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_http.c
cc -c -o ot_livesync.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_livesync.c
cc -c -o ot_rijndael.o -I../libowfat -DGIT_VERSION=_git_or_commit_not_found_ -Wall -pipe -pthread -Wextra  -O3 -DWANT_IP_FROM_PROXY -DWANT_NO_AUTO_FREE ot_rijndael.c
cc -o opentracker opentracker.o trackerlogic.o scan_urlencoded_query.o ot_mutex.o ot_stats.o ot_vector.o ot_clean.o ot_udp.o ot_iovec.o ot_fullscrape.o ot_accesslist.o ot_http.o ot_livesync.o ot_rijndael.o -L../libowfat -lowfat -pthread
/usr/bin/ld: ../libowfat/libowfat.a(io_fd.o):(.bss+0xb0): multiple definition of `first_deferred'; ../libowfat/libowfat.a(io_close.o):(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:87: opentracker] Error 1

**Comment by 1265578519** [comment]
从错误结果看，错误发生在libowfat，在 README 上有说明，不同系统需要使用的libowfat版本不一样
debian 11试一下libowfat 0.33，删除现有的libowfat目录，然后下载、解压、并且移动目录
wget https://www.fefe.de/libowfat/libowfat-0.33.tar.xz
tar Jxvf libowfat-0.33.tar.xz

**Comment by 1265578519** [comment]
如果libowfat 0.33依旧发生报错，则尝试0.31

**Comment by baton411** [comment]
Thank you, it worked, I think I’m not the only one who encountered this, it’s worth writing about it in the readme.
