### ISSUE TITLE
CPU load problem

### ISSUE THREAD

**Issue by baton411** [1265578519/OpenTracker#6]
It seems that the problem with the processor is 100% not only not fixed, but only worse, and this is not an attack, since the number of packets does not increase, the statistics page is not used at all and is blocked at the iptables
![1](https://github.com/user-attachments/assets/9650d418-b707-426b-af8d-58572f4c4192)
![2](https://github.com/user-attachments/assets/8d2f6ee4-082b-42f1-99b1-c033d741f87e)

**Comment by 1265578519** [comment]
高cpu占用有两种情况，在 README 和其中的url链接里有介绍
第一种
一个已知BUG，开机自动启动进程引起，进程自身占用99%的高额CPU，可以通过 killall -9 opentracker 杀进程重新启动进程来恢复（不知道是什么原因引起开机自启动产生的BUG，杀死进程并重启进程后一切正常）
![image](https://github.com/user-attachments/assets/596796ba-5e85-4c45-b97f-cfdc0010ee47)

第二种
也是你截图中的情况，system系统内核占用了大量的CPU，这点在 README 最尾部有说明需要优化内核参数
![image](https://github.com/user-attachments/assets/ab24d331-1ecc-4a47-9dbe-4759e45c7bf9)
1.打开文件数
```
ulimit -n 1048576
echo "* soft nofile 1048576" >> /etc/security/limits.conf
echo "* hard nofile 1048576" >> /etc/security/limits.conf
```
2.ksoftirqd内核进程占用高CPU的优化，禁用防火墙和确认lsmod中不存在加载nf驱动模块
centos7关闭防火墙并且禁用nf驱动模块，对于其它系统的关闭方法请使用搜索引擎
```
yum -y install iptables-services;service ip6tables stop;chkconfig ip6tables off;service iptables stop;chkconfig iptables off;systemctl stop firewalld;systemctl disable firewalld
```
关闭防火墙后，通过 lsmod 指令确认驱动模块加载情况，不能有包含"nf"开头的模块
![image](https://github.com/user-attachments/assets/32be576e-320b-4707-a010-aabc399c4a7c)
此时通过top任务管理器，能够观察到ksoftirqd进程CPU占用大幅度下降
![image](https://github.com/user-attachments/assets/5d7dfbc2-f04e-4139-99bf-94b276497b39)

**Comment by 1265578519** [comment]
正常运行后，在单核心的vps服务器中，opentracker每秒轻松处理1w3千请求量
Concurrency Level:      100
Time taken for tests:   7.310 seconds
Complete requests:      100000
Failed requests:        0
Write errors:           0
Total transferred:      17200000 bytes
HTML transferred:       10600000 bytes
Requests per second:    13680.35 [#/sec] (mean)
Time per request:       7.310 [ms] (mean)
Time per request:       0.073 [ms] (mean, across all concurrent requests)
Transfer rate:          2297.87 [Kbytes/sec] received

**Comment by baton411** [comment]
nf is currently not active at all, the tracker works for me only via udp, tcp is blocked via iptables, kernel overflow is excluded

**Comment by baton411** [comment]
![image](https://github.com/user-attachments/assets/27487013-57d9-4727-8c53-35987d89cef8)

**Comment by baton411** [comment]
![image](https://github.com/user-attachments/assets/97308843-e411-4af3-b8e7-0c356963a18e)

**Comment by 1265578519** [comment]
停止占用cpu的进程，可以的话暂停DNS解析，确保系统处于空负载
检查下当前可用的CPU Freq，和MIPS评分是否每个cpu核心大于等于2000
```
yum -y install glibc.i686 wget tar bzip2
wget --no-check-certificate https://downloads.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_x86_linux_bin.tar.bz2 -O /root/p7zip_16.02_x86_linux_bin.tar.bz2
tar -xjvf p7zip_16.02_x86_linux_bin.tar.bz2
cd /root/p7zip_16.02/bin
./7za b

```

**Comment by baton411** [comment]
https://github.com/user-attachments/assets/2e8b1ec9-b47a-42b5-817f-66840aca3b13

So I recorded a video and only stopped the opentracker process and the entire load went away

**Comment by 1265578519** [comment]
你可以看一下top吗，htop不够详细，没有系统指标，看一下st值是否很高？

6.7% us — 用户空间占用CPU的百分比。
0.4% sy — 内核空间占用CPU的百分比。
0.0% ni — 改变过优先级的进程占用CPU的百分比
92.9% id — 空闲CPU百分比
0.0% wa — IO等待占用CPU的百分比
0.0% hi — 硬中断（Hardware IRQ）占用CPU的百分比
0.0% si — 软中断（Software Interrupts）占用CPU的百分比
0.0% st — 虚拟化时响应等待时间（steal time）超售所占用CPU的百分比

st值应当始终保持为0.0%，如果有任何浮动，代表该主机存在超售行为

**Comment by 1265578519** [comment]
你的视频中，netdata可以看到并没有什么网络资源访问，消耗宽带在1Mbps左右，所以我比较怀疑是CPU性能问题，观察st指标，和使用7za评分
或者因为libowfat的原因，工作在你这个系统可能兼容问题，可以尝试更换centos6或centos7

**Comment by baton411** [comment]
my system is debian 12, this server a couple of days ago was running on the previous version of opentracker from you, there were similar problems but they only happened once an hour, and with the new version the load is almost always, the vps has a good processor, I provide tests:  https://browser.geekbench.com/v5/cpu/22947844
(the tracker was turned off before measurement)

**Comment by baton411** [comment]
this is the moment when it has not yet started to overload the CPU
![image](https://github.com/user-attachments/assets/5e9bbb4f-1f85-463f-8a38-819f5d7fb9aa)

**Comment by baton411** [comment]
and here is the moment when the process began to overload the CPU
![image](https://github.com/user-attachments/assets/94a61815-0484-4df7-b315-564f2efc484d)

**Comment by 1265578519** [comment]
现在从top看到，st基本为0，geekbench显示的性能评分很好，可以排除是CPU性能原因
现在有2个方向，我更倾向于第二点
1.libowfat的原因
2.opentracker触发了函数死循环引起bug

对于第二点，你需要做的有
这是一个例子，你需要使用opentracker.debug来运行，以便在调试模式下获得进程符号，出现持续高cpu的时候，此时输入bt，然后t 0、t 1切换不同线程进行bt，查看opentracker当前在做什么，为什么发生了cpu 100%
```
yum -y install gdb
```
```
[root@tracker ~]# cd /home/OpenTracker-master/opentracker
[root@tracker opentracker]# gdb --args ./opentracker.debug -f opentracker.conf.sample -p 81 -P 8080 -p 6961 -P 6961 -p 2710 -P 2710
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/OpenTracker-master/opentracker/opentracker.debug...done.
(gdb) run
Starting program: /home/OpenTracker-master/opentracker/./opentracker.debug -f opentracker.conf.sample -p 81 -P 8080 -p 6961 -P 6961 -p 2710 -P 2710
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Binding socket type TCP to address [::]:81... success.
Binding socket type UDP to address [::]:8080... success.
Binding socket type TCP to address [::]:6961... success.
Binding socket type UDP to address [::]:6961... success.
Binding socket type TCP to address [::]:2710... success.
Binding socket type UDP to address [::]:2710... success.
Dropping to user nobody.
[New Thread 0x7ffff73c7700 (LWP 13267)]
[New Thread 0x7ffff6bc6700 (LWP 13268)]
 installing 0 workers on udp socket -1

bt
^C
Program received signal SIGINT, Interrupt.
0x00007ffff76da0e3 in epoll_wait () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 zlib-1.2.7-21.el7_9.x86_64
(gdb) bt
#0  0x00007ffff76da0e3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000000040e368 in io_waituntil2 ()
#2  0x000000000040287a in server_mainloop (args=0x0) at opentracker.c:294
#3  0x0000000000403c42 in main (argc=15, argv=0x7fffffffe4a8) at opentracker.c:693
(gdb) t 0
Thread ID 0 not known.
(gdb) bt
#0  0x00007ffff76da0e3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000000040e368 in io_waituntil2 ()
#2  0x000000000040287a in server_mainloop (args=0x0) at opentracker.c:294
#3  0x0000000000403c42 in main (argc=15, argv=0x7fffffffe4a8) at opentracker.c:693
(gdb) t 1
[Switching to thread 1 (Thread 0x7ffff7fed740 (LWP 13263))]
#0  0x00007ffff76da0e3 in epoll_wait () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff76da0e3 in epoll_wait () from /lib64/libc.so.6
#1  0x000000000040e368 in io_waituntil2 ()
#2  0x000000000040287a in server_mainloop (args=0x0) at opentracker.c:294
#3  0x0000000000403c42 in main (argc=15, argv=0x7fffffffe4a8) at opentracker.c:693
(gdb) t 2
[Switching to thread 2 (Thread 0x7ffff73c7700 (LWP 13267))]
#0  0x00007ffff76a09fd in nanosleep () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff76a09fd in nanosleep () from /lib64/libc.so.6
#1  0x00007ffff76d12d4 in usleep () from /lib64/libc.so.6
#2  0x0000000000408ce6 in clean_worker (args=0x0) at ot_clean.c:123
#3  0x00007ffff7bc6ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff76d9b0d in clone () from /lib64/libc.so.6
(gdb) t 3
[Switching to thread 3 (Thread 0x7ffff6bc6700 (LWP 13268))]
#0  0x00000000004064c3 in stats_top_txt (reply=0x7ffff0005e30 "\330\a", amount=100) at ot_stats.c:315
315	      int idx = amount - 1; while( (idx >= 0) && ( peer_list->peer_count > top100c[idx].val ) ) --idx;
(gdb) bt
#0  0x00000000004064c3 in stats_top_txt (reply=0x7ffff0005e30 "\330\a", amount=100) at ot_stats.c:315
#1  0x0000000000407705 in stats_make (iovec_entries=0x7ffff6bc5f04, iovector=0x7ffff6bc5ef8, 
    mode=TASK_STATS_TOP100) at ot_stats.c:620
#2  0x0000000000407b2b in stats_worker (args=0x0) at ot_stats.c:752
#3  0x00007ffff7bc6ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff76d9b0d in clone () from /lib64/libc.so.6
(gdb) t 4
Thread ID 4 not known.
(gdb) gcore
warning: target file /proc/13263/cmdline contained unexpected null characters
Saved corefile core.13263
(gdb) quit
A debugging session is active.

	Inferior 1 [process 13263] will be killed.

Quit anyway? (y or n) y
[root@tracker opentracker]#
```

除了gdb外，perf也是一个很好的性能分析工具
直接运行debug进程，使用perf取得报告，对于perf在读取报告的时候可能会消耗vps较多的内存，根据perf.data文件文件大小耗费时长和内存
安装
```
yum -y install perf
```
运行要分析的程序
```
perf record -g ./opentracker.debug -f opentracker.conf.sample -p 81 -P 8080 -p 6961 -P 6961 -p 2710 -P 2710
```
读取报告，加载刚刚运行完成后生成在当前文件夹的perf.data文件
```
perf report
```
报告如图显示，服务器极高CPU占用的函数为stats_top_txt，你需要获得你仅使用udp跟踪器下发现的高cpu函数
![O26SLRA S{D`E{(UJQB86N](https://github.com/1265578519/OpenTracker/assets/6442439/c92f898f-3322-4994-bd9b-a33aa22b0f5f)

**Comment by baton411** [comment]
Immediately after starting the process can run without problems for an hour, but after a while it starts to overload the CPU, I won't be able to keep the ssh connection for an hour, the connection will drop sooner, I need to somehow run debugging so that it is written to file

**Comment by 1265578519** [comment]
正常使用opentracker.debug运行后台进程
./opentracker.debug -f opentracker.conf.sample -p 8080 -P 8080 &

比如说发现进程异常持续死循环Cpu 100%的时候
运行 gdb ./opentracker.debug 当前进程的pid号

进入gdb后输入gcore
然后ctrl+d退出
这样就弄好了一个快照位于当前目录下文件名为core.pid
1.5G        core.3205

获取pid可以用这个命令
top -b -n 1 |grep opentracker

随后可以通过core文件来调试
gdb /home/OpenTracker-master/opentracker/opentracker.debug core.3205文件
查看每个线程的bt，t n是切换线程

然后t 0
bt
t 1
bt
t 2
bt
t 3
bt

**Comment by baton411** [comment]
this method did not work, the log was not created after gdb ./opentracker.debug

**Comment by 1265578519** [comment]
补齐目录试一下？
gdb /home/OpenTracker-master/opentracker/opentracker.debug 当前进程的pid号

**Comment by baton411** [comment]
and this method worked, I’m sending the file: https://cdn.srv00.com/core.2805291 (github won't let me upload the file, I'll leave it on my web server)
![image](https://github.com/user-attachments/assets/210b132e-033a-4433-b203-3f0553114d5f)

**Comment by 1265578519** [comment]
> 随后可以通过core文件来调试 gdb /home/OpenTracker-master/opentracker/opentracker.debug core.3205文件 查看每个线程的bt，t n是切换线程
> 
> 然后t 0 bt t 1 bt t 2 bt t 3 bt
> 
> 可以尝试2-3次复现CPU100%结果，观察每次线程内容是否相同没有发生改变


你现在可以执行这个bt指令的操作，如果我来执行还需要对应的 opentracker.debug 的二进制文件用于打开core

**Comment by 1265578519** [comment]
对于文件上传，可以分卷压缩25MB，并且增加后缀名为.zip
如图所示
![image](https://github.com/user-attachments/assets/3029517e-b220-4cd0-a699-1f962197ffed)

**Comment by baton411** [comment]
[opentracker.zip](https://github.com/user-attachments/files/17334280/opentracker.zip)
here is the binary

**Comment by 1265578519** [comment]
成功使用二进制文件加载了core，这是分析结果，性能瓶颈在handle_accept函数上，看起来是锁互斥，你确定内核打开文件依旧修改了吗？
如果确认已经改成1048576但是发生这种情况，可以使用这个工具来确认
```
yum -y install lsof
```
根据软件的pid进行排序显示
```
lsof -n | awk '{ print $2; }' | uniq -c | sort -rn | head
```
查看单个pid进程的限制打开文件大小最大数量，可以查看修改系统打开文件数量后是否生效了
```
cat /proc/28492/limits | grep files
```

系统默认为1024，触发这个限制会导致handle_accept函数上锁互斥引起占用CPU100%

如果你确认了不是ulimit问题，我发送这份报告给开发者来尝试优化源代码

```
[root@VM-0-16-centos ~]# gdb ./opentracker.debug core.2805291
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/opentracker.debug...done.

warning: core file may not match specified executable file.
[New LWP 2805291]
[New LWP 2805292]
[New LWP 2805293]
[New LWP 2805294]

warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)

warning: Could not load shared library symbols for 2 libraries, e.g. /lib/x86_64-linux-gnu/libpthread.so.0.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `./opentracker.debug'.
#0  0x00007fdb49cdc60f in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.3.x86_64
(gdb) bt
#0  0x00007fdb49cdc60f in ?? ()
#1  0x000000006be5000a in ?? ()
#2  0x0000000330a80988 in ?? ()
#3  0x00007ffd30a7e6a0 in ?? ()
#4  0x00007ffd30a7e69c in ?? ()
#5  0x00007ffd30a80998 in ?? ()
#6  0x00005579b0017cba in socket_accept6 ()
#7  0x00005579b000bfd6 in handle_accept (serversocket=3) at opentracker.c:254
#8  0x00005579b000c0a7 in server_mainloop (args=0x0) at opentracker.c:314
#9  0x00005579b000d616 in main (argc=1, argv=0x7ffd30a80988) at opentracker.c:805
(gdb) t 0
Thread ID 0 not known.
(gdb) bt
#0  0x00007fdb49cdc60f in ?? ()
#1  0x000000006be5000a in ?? ()
#2  0x0000000330a80988 in ?? ()
#3  0x00007ffd30a7e6a0 in ?? ()
#4  0x00007ffd30a7e69c in ?? ()
#5  0x00007ffd30a80998 in ?? ()
#6  0x00005579b0017cba in socket_accept6 ()
#7  0x00005579b000bfd6 in handle_accept (serversocket=3) at opentracker.c:254
#8  0x00005579b000c0a7 in server_mainloop (args=0x0) at opentracker.c:314
#9  0x00005579b000d616 in main (argc=1, argv=0x7ffd30a80988) at opentracker.c:805
(gdb) t 1
[Switching to thread 1 (LWP 2805291)]
#0  0x00007fdb49cdc60f in ?? ()
(gdb) bt
#0  0x00007fdb49cdc60f in ?? ()
#1  0x000000006be5000a in ?? ()
#2  0x0000000330a80988 in ?? ()
#3  0x00007ffd30a7e6a0 in ?? ()
#4  0x00007ffd30a7e69c in ?? ()
#5  0x00007ffd30a80998 in ?? ()
#6  0x00005579b0017cba in socket_accept6 ()
#7  0x00005579b000bfd6 in handle_accept (serversocket=3) at opentracker.c:254
#8  0x00005579b000c0a7 in server_mainloop (args=0x0) at opentracker.c:314
#9  0x00005579b000d616 in main (argc=1, argv=0x7ffd30a80988) at opentracker.c:805
(gdb) t 2
[Switching to thread 2 (LWP 2805292)]
#0  0x00007fdb49ca1485 in ?? ()
(gdb) bt
#0  0x00007fdb49ca1485 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) t 3
[Switching to thread 3 (LWP 2805293)]
#0  0x00007fdb49ca1485 in ?? ()
(gdb) bt
#0  0x00007fdb49ca1485 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) t 4
[Switching to thread 4 (LWP 2805294)]
#0  0x00007fdb49c57e96 in ?? ()
(gdb) bt
#0  0x00007fdb49c57e96 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) t 5
Thread ID 5 not known.
(gdb)
```

**Comment by baton411** [comment]
![image](https://github.com/user-attachments/assets/0443013f-29d0-42fd-b6e2-847cfb36d68a)

**Comment by baton411** [comment]
[opentracker.zip](https://github.com/user-attachments/files/17334756/opentracker.zip)
this is the normal startup binary

**Comment by 1265578519** [comment]
两个值都需要正确设置为1048576，从你的截图中看到是系统默认值1024，没有成功优化内核设置，你的设置可能是错误的，因为打开文件显示数值还是1024
![image](https://github.com/user-attachments/assets/c5f0bd51-5190-4624-951e-ce4c92b3f8fa)

这是centos中的设置方法

> 1.打开文件数
> 
> ```
> ulimit -n 1048576
> echo "* soft nofile 1048576" >> /etc/security/limits.conf
> echo "* hard nofile 1048576" >> /etc/security/limits.conf
> ```

对于debian 11我不熟悉，需要查阅下搜索引擎，如何设置打开文件数

**Comment by 1265578519** [comment]
查阅后，设置方法是一样的
cat /etc/security/limits.conf
![image](https://github.com/user-attachments/assets/0c632191-8f15-4b63-b31c-286a84011a05)

ulimit -a
![image](https://github.com/user-attachments/assets/f7d2674c-fba3-4fd5-aba5-6ce2820079c6)

成功设置后重新运行进程，此时看到就是1048576
cat /proc/28492/limits | grep files

**Comment by 1265578519** [comment]
正确设置ulimit后，你现在使用这个命令，可以查到成功突破4124
lsof -n | awk '{ print $2; }' | uniq -c | sort -rn | head

虽然实际上ulimit限制显示是1024，但是Linux应该是用4字节作为计算，也就是4124达到阈值，修改打开文件后就可以突破4124

**Comment by baton411** [comment]
![image](https://github.com/user-attachments/assets/f1ab9ade-c471-47ed-a242-0031747c62c1)
the number of files increased in ulimit -a but did not increase in cat /proc/2813980/limits | grep files

**Comment by 1265578519** [comment]
这是查阅搜索引擎，我对英文不熟悉，看起来Debian可能不支持*号，需要修改成nobody
```
echo "nobody soft nofile 1048576" >> /etc/security/limits.conf
echo "nobody hard nofile 1048576" >> /etc/security/limits.conf
```
https://blog.csdn.net/winnyrain/article/details/134299581
https://lists.debian.org/debian-user/2018/05/msg01025.html
https://groups.google.com/g/linux.debian.bugs.dist/c/-wNGfx9Hxpo

**Comment by 1265578519** [comment]
其中一篇文章提到Debian
```
Creating the file /etc/systemd/system.conf.d/limits.conf and writing "[Manager]" and "DefaultLimitNOFILE=65536" in it.

gnome-terminal is started as a user service, no as a system service.
So what you most likely need to change is to update
/etc/systemd/user.conf(.d)

See man user.conf.d
```

**Comment by 1265578519** [comment]
太棒了，现在你观察CPU占用情况是否还会发生100%现象

你也可以分享下你使用哪种方法成功修改了Debian的ulimit

修改成功为1048576，现在可以成功利用超过4124了


> 根据软件的pid进行排序显示
> 
> ```
> lsof -n | awk '{ print $2; }' | uniq -c | sort -rn | head
> ```

**Comment by baton411** [comment]
it looks like it helped, thank you, I think it would be worth including this in the startup manual, its standard Debian 12, which means that everyone will have a problem of a similar nature

**Comment by 1265578519** [comment]
太棒了，看来你因为handle_accept函数引发CPU100%问题已经解决，原因是没有正确设置打开文件数量
你能描述下你是如何在Debian上修改成功的吗

**Comment by baton411** [comment]
/etc/security/limits.conf >
root soft nofile 5000000
root hard nofile 5000000
nobody soft nofile 5000000
nobody hard nofile 5000000

/etc/sysctl.conf >
fs.file-max = 5000000

/etc/systemd/system.conf > 
DefaultLimitNOFILE=5000000

/etc/systemd/user.conf >
DefaultLimitNOFILE=5000000

**Comment by 1265578519** [comment]
README 上添加了一些说明信息，和添加了一个禁用AnonHugePages使用内存
https://github.com/1265578519/OpenTracker/commit/07a2d2e254a5ce0ed67b0fc86e74fef450074a1a
https://github.com/1265578519/OpenTracker/commit/e7a7e30ae46b32fa3eb532b6e6de2116fa2f0fcc
